syntax = "proto3";

package super_school;

import "user.proto";

service ParentUserService {
  rpc FindParentList(FindParentListRequest) returns (FindParentListResponse);
}

message FindParentListRequest {
  int32 page = 1;
  int32 limit = 2;
  optional string name = 3; // 완전일치 검색 (컴플라이언스 5.13)
  int32 schoolId = 4;
  optional string email = 5; // 완전일치 검색
  optional int32 childGrade = 6; // 자녀 학년
  optional int32 childKlass = 7; // 자녀 반
  optional int32 childNumber = 8; // 자녀 번호
}

message FindParentListResponse {
  repeated UserSimpleInfo data = 1;
  int32 totalCount = 2;
  int32 currentPage = 3;
  int32 limit = 4;
  int32 totalPage = 5;
  bool hasNext = 6;
  bool hasPrev = 7;
}

